# .github/workflows/sync-to-r2.yml

name: Sync to Cloudflare R2 (Corrected)

on:
  push:
    branches:
      - main  # 或者你的主分支名，比如 master

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync files to R2 using AWS CLI
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.R2_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          
          # 修正了此处的语法，移除了错误的符号
          AWS_S3_ENDPOINT: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
          
          AWS_REGION: "auto"
